id = "railwise"
name = "RAILWISE"
description = "The open source coding agent."
version = "1.2.8"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/railwise"

[agent_servers.railwise]
name = "RAILWISE"
icon = "./icons/railwise.svg"

[agent_servers.railwise.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/railwise/releases/download/v1.2.8/railwise-darwin-arm64.zip"
cmd = "./railwise"
args = ["acp"]

[agent_servers.railwise.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/railwise/releases/download/v1.2.8/railwise-darwin-x64.zip"
cmd = "./railwise"
args = ["acp"]

[agent_servers.railwise.targets.linux-aarch64]
archive = "https://github.com/anomalyco/railwise/releases/download/v1.2.8/railwise-linux-arm64.tar.gz"
cmd = "./railwise"
args = ["acp"]

[agent_servers.railwise.targets.linux-x86_64]
archive = "https://github.com/anomalyco/railwise/releases/download/v1.2.8/railwise-linux-x64.tar.gz"
cmd = "./railwise"
args = ["acp"]

[agent_servers.railwise.targets.windows-x86_64]
archive = "https://github.com/anomalyco/railwise/releases/download/v1.2.8/railwise-windows-x64.zip"
cmd = "./railwise.exe"
args = ["acp"]
