id = "yonsoon"
name = "YONSOON (甬算)"
description = "The open source coding agent."
version = "1.2.6"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/yonsoon"

[agent_servers.yonsoon]
name = "YONSOON (甬算)"
icon = "./icons/yonsoon.svg"

[agent_servers.yonsoon.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/yonsoon/releases/download/v1.2.6/yonsoon-darwin-arm64.zip"
cmd = "./yonsoon"
args = ["acp"]

[agent_servers.yonsoon.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/yonsoon/releases/download/v1.2.6/yonsoon-darwin-x64.zip"
cmd = "./yonsoon"
args = ["acp"]

[agent_servers.yonsoon.targets.linux-aarch64]
archive = "https://github.com/anomalyco/yonsoon/releases/download/v1.2.6/yonsoon-linux-arm64.tar.gz"
cmd = "./yonsoon"
args = ["acp"]

[agent_servers.yonsoon.targets.linux-x86_64]
archive = "https://github.com/anomalyco/yonsoon/releases/download/v1.2.6/yonsoon-linux-x64.tar.gz"
cmd = "./yonsoon"
args = ["acp"]

[agent_servers.yonsoon.targets.windows-x86_64]
archive = "https://github.com/anomalyco/yonsoon/releases/download/v1.2.6/yonsoon-windows-x64.zip"
cmd = "./yonsoon.exe"
args = ["acp"]
