name: railwise

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  railwise:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /railwise') ||
      startsWith(github.event.comment.body, '/railwise')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run railwise
        uses: anomalyco/railwise/github@latest
        env:
          RAILWISE_API_KEY: ${{ secrets.RAILWISE_API_KEY }}
          RAILWISE_PERMISSION: '{"bash": "deny"}'
        with:
          model: railwise/claude-opus-4-5
