name: yonsoon

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  yonsoon:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /yonsoon') ||
      startsWith(github.event.comment.body, '/yonsoon')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run yonsoon
        uses: anomalyco/yonsoon/github@latest
        env:
          YONSOON_API_KEY: ${{ secrets.YONSOON_API_KEY }}
          YONSOON_PERMISSION: '{"bash": "deny"}'
        with:
          model: yonsoon/claude-opus-4-5
